#!/usr/bin/env sh
USER=""
HOST=""
SOURCE=""
DIST=""

opts() {
  while (("$#")); do
    case "$1" in
      -u | --user)
			if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
				USER=$2
				shift 2
			else
				echo "Error: Argument for $1 is missing" >&2
				exit 1
			fi
      ;;
      -h | --host)
			if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
				HOST=$2
				shift 2
			else
				echo "Error: Argument for $1 is missing" >&2
				exit 1
			fi
      ;;
      -s | --source)
			if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
				HOST=$2
				shift 2
			else
				echo "Error: Argument for $1 is missing" >&2
				exit 1
			fi
      ;;
      -d | --destination)
			if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
				HOST=$2
				shift 2
			else
				echo "Error: Argument for $1 is missing" >&2
				exit 1
			fi
      ;;
    esac
  done
}

scp "$SOURCE" "$USER"@"$HOST":"$DIST"
